const fs = require(fs);
const path = require(path);

const base = C:/Users/MartijnvanderKolk/Documents/GitHub/Open-Calc/apps/sbo/src/app/api/projects/[id]/change-orders;

const files = {};

files[route.ts] = [
  'import { NextResponse } from next/server;',
  'import { getDefaultUserId } from @/lib/auth;',
  'import { prisma } from @/lib/db;',
  'import { z } from zod;',
  '',
  'const createChangeOrderSchema = z.object({',
  '  title: z.string().min(1, Titel is verplicht),',
  '  description: z.string().nullable().optional(),',
  '  type: z.enum([EXTRA, LESS]).default(EXTRA),',
  '  estimateId: z.string().nullable().optional(),',
  '});',
  '',
  'export async function GET(',
  '  request: Request,',
  '  { params }: { params: Promise<{ id: string }> }',
  ') {',
  '  try {',
  '    const userId = await getDefaultUserId();',
  '    const { id } = await params;',
  '',
  '    const project = await prisma.project.findFirst({',
  '      where: { id, userId },',
  '    });',
  '',
  '    if (\!project) {',
  '      return NextResponse.json(',
  '        { error: Project niet gevonden },',
  '        { status: 404 }',
  '      );',
  '    }',
  '',
  '    const changeOrders = await prisma.changeOrder.findMany({',
  '      where: { projectId: id },',
  '      include: { lines: true },',
  '      orderBy: { number: desc },',
  '    });',
  '',
  '    return NextResponse.json(changeOrders);',
  '  } catch (error) {',
  '    console.error(Error fetching change orders:, error);',
  '    return NextResponse.json(',
  '      { error: Er is een fout opgetreden bij het ophalen van meer/minderwerk },',
  '      { status: 500 }',
  '    );',
  '  }',
  '}',
  '',
  'export async function POST(',
  '  request: Request,',
  '  { params }: { params: Promise<{ id: string }> }',
  ') {',
  '  try {',
  '    const userId = await getDefaultUserId();',
  '    const { id } = await params;',
  '',
  '    const project = await prisma.project.findFirst({',
  '      where: { id, userId },',
  '    });',
  '',
  '    if (\!project) {',
  '      return NextResponse.json(',
  '        { error: Project niet gevonden },',
  '        { status: 404 }',
  '      );',
  '    }',
  '',
  '    const body = await request.json();',
  '    const validated = createChangeOrderSchema.safeParse(body);',
  '',
  '    if (\!validated.success) {',
  '      const firstError = validated.error.issues[0];',
  '      return NextResponse.json(',
  '        { error: firstError?.message || Validatie fout },',
  '        { status: 400 }',
  '      );',
  '    }',
  '',
  '    const lastChangeOrder = await prisma.changeOrder.findFirst({',
  '      where: { projectId: id },',
  '      orderBy: { number: desc },',
  '      select: { number: true },',
  '    });',
  '',
  '    const nextNumber = (lastChangeOrder?.number ?? 0) + 1;',
  '',
  '    const changeOrder = await prisma.changeOrder.create({',
  '      data: {',
  '        number: nextNumber,',
  '        title: validated.data.title,',
  '        description: validated.data.description ?? null,',
  '        type: validated.data.type,',
  '        estimateId: validated.data.estimateId ?? null,',
  '        projectId: id,',
  '      },',
  '      include: { lines: true },',
  '    });',
  '',
  '    return NextResponse.json(changeOrder, { status: 201 });',
  '  } catch (error) {',
  '    console.error(Error creating change order:, error);',
  '    return NextResponse.json(',
  '      { error: Er is een fout opgetreden bij het aanmaken van meer/minderwerk },',
  '      { status: 500 }',
  '    );',
  '  }',
  '}',
].join(\n);

for (const [filename, content] of Object.entries(files)) {
  const fp = path.join(base, filename);
  fs.writeFileSync(fp, content, utf8);
  console.log(Written:, fp);
}